### ISSUE TITLE
Multi layer and Intersection Area in Leaflet

### ISSUE THREAD

**Issue by tarkmark** [Wildhoney/Leaflet.FreeDraw#42] opened 2015-01-06 12:23 UTC
Dear Adam,
Your FreeDraw plugin at "http://freedraw.herokuapp.com/"
is very successful and flexible for drawing poligon. Congratulations for it. Plugin can combine two different poligon if they have intersection area (like union of sets). Is that possible to remove some parts of the poligon by drawing a different poligon with remove module.
Can we define a new layer with different properties. So when I choose a layer, I intent to modify only that layer .
thanks

**Comment by jekuno** [comment] 2015-04-29 16:34
This is a duplicate of issue #28. Please have a look at that issue for details.

**Closed** 2016-09-28 09:29 UTC
